# 例外オブジェクト
Rubyでは例外も例外クラスのインスタンス(例外オブジェクト)になっている。<br>
すべての例外の祖先のクラスである。<br>
例外オブジェクトのメソッドを呼び出すことで、発生した例外に関する情報を取得することができる。

# 例外を捕捉
### 構文
```
begin
  # 例外が起こりうる処理
rescue
  # 例外が発生した場合の処理
end
```
### 例外オブジェクトから情報を取得する構文
```
begin
  # 例外が起こりうる処理
rescue => 例外オブジェクトを格納する変数
  # 例外が発生した場合の処理
end
```
例外オブジェクトを格納する変数の名前は自由に付けることができるが、
exceptionの省略形としてeやexのような名前をよく見かける。

### クラスを指定して捕捉する例外を限定
```
begin
  # 例外が起こりうる処理
rescue 捕捉したい例外クラス
  # 例外が発生した場合の処理
end
```
指定した例外クラス以外の例外が発生した場合は、例外は捕捉されない(プログラムが異常終了する)<br>
rescue節を複数書くことで、異なる例外クラスに対応することもできる。また、一つのrescue節に複数の例外クラスを指定することもできる。<br>
例外オブジェクトを変数に格納することも可能

# インスタンスメソッド
| メソッド | 意味 |
| :--- | :--- |
| backtrace | バックトレース情報(つまりメソッドの呼び出し履歴)を配列にして返す。 |
| cause | 自身の前の例外を返す。存在しない場合は`nil` |
| exception | 引数を指定しない場合は`self`を返す。|
| inspect | 自身のクラス名とメッセージを文字列にして返す。 |
| message | 例外発生次のエラーメッセージを返す。 |

例外オブジェクトを記載しない場合でも、以下のオブジェクトに内容が自動的にセットされます。
- `$!` : 最後に発生した例外オブジェクト
- `$@` : 最後に発生した例外の位置情報


```
x = 0

begin
  # 0除算をした場合
  p 10 / x
rescue => ex
  p ex.class
  p ex.message
  p ex.backtrace
  p "0除算をしています"  # メッセージを出力したい場合
end

begin
  1/0
rescue ZeroDivisionError
  puts"0で除算しました"
end. #=>0で除算しました

```
